version: "3.9"

services:

  play-server:
    build:
      context: ./docker/play-server
    ports:
      - "3003:3003"
      - "9228:9229"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    entrypoint: bash -c "npm install && npm run start:debug"
  
  cli:
    build:
      context: ./docker/cli
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
